config/routes.rb
Rails.application.routes.draw do
  root 'static#index'
  get '/terms', to: 'static#terms'
  get '/rules', to: 'static#rules'
  get '/credits', to: 'static#credits'
  get '/privacy_policy', to: 'static#privacy_policy'

  resources :games, only: %i[index show create destroy], shallow: true do
    member do
      get :paticipates
    end
    resources :users, only: %i[edit], shallow: true do
      post :authorize
      resources :user_hands, only: %i[show edit destroy]
      resources :user_supports, only: %i[edit destroy]
    end
    resources :game_details, only: %i[index]
  end

  resources :cpu_games, only: %i[show create destroy], shallow: true do
    resources :users, only: %i[show edit], shallow: true do
      resources :user_hands, only: %i[show edit destroy]
      resources :user_supports, only: %i[show edit destroy]
    end
    resources :game_details, only: %i[index]
  end

  get '/login_as/:user_id', to: 'dev/user_sessions#login_as' unless Rails.env.production?
end

app/controllers/cpu_games_controller.rb
class CpuGamesController < ApplicationController
  skip_before_action :require_login, only: %i[create]
  before_action :set_game, only: %i[show destroy]

  def show; end

  def create
    Game.transaction do
      respond_to do |format|
        @game = Game.new(field: Field.all.sample)
        host = @game.users.build(role: :host, character: Character.all.sample)
        @game.users.build(role: :guest, character: Character.all.sample, user_token_digest: 'cpu_token')
        host.set_user_token

        if @game.create_game_and_set_user_cards!
          remember(host)
          format.html { redirect_to cpu_game_path(@game) }
          format.json { render :show, status: :ok, location: @game }
          @game.notify_to_game('ゲームを作成しました！')
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /games/1
  def destroy
    @game.destroy
    redirect_to root_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
    @host = @game.host
    @guest = @game.guest
  end
end

app/helpers/cpu_games_helper.rb
module CpuGamesHelper
end

app/views/cpu_games/_game.html.haml
= turbo_frame_tag game do
  = render "background", game: game do
    .d-flex.flex-column.justify-content-center
      - if current_user.host_role?
        .d-flex.flex-row.justify-content-center.mb-5
          = render 'users/user', game: game, user: @guest
        .d-flex.flex-row.justify-content-center.mt-5
          = render 'users/user', game: game, user: @host
      - elsif current_user.guest_role?
        .d-flex.flex-row.justify-content-center.mb-5
          = render 'users/user', game: game, user: @host
        .d-flex.flex-row.justify-content-center.mt-5
          = render 'users/user', game: game, user: @guest

app/views/cpu_games/_game_card.html.haml
.carousel-item{class: "#{'active' if game_counter == 0}", style: "height: 800px"}
  = render "background", game: game do
    .d-flex.flex-column.justify-content-center
      .d-flex.flex-row.justify-content-center
        %h2.text-white ホスト
      .d-flex.flex-row.justify-content-center
        = image_tag game.host.character.card_image, class: "card mx-4"
      .d-flex.flex-row.justify-content-center.mt-2
        %h2.text-primary VS
      .d-flex.flex-row.justify-content-center
        = image_tag game.guest.character.card_image, class: "card mx-4"
      .d-flex.flex-row.justify-content-center.mt-2
        %h2.text-white ゲスト
      .d-flex.flex-row.justify-content-center.mt-3
        = button_to 'ゲームに参加する', user_authorize_path(game_id: game.id, user_id: game.guest.id), method: :post, class: 'btn btn-primary', data: { turbo: false }

app/views/cpu_games/_game_frame.html.haml
= turbo_frame_tag game, src: game_path(game, frame: true)

app/views/cpu_games/edit.html.haml
= render "modal" do
  = render "form", game: @game

app/views/cpu_games/show.html.haml
- set_meta_tags title: 'ゲーム', noindex: true
-# flash message
= turbo_stream_from dom_id(@game, 'flashes')
= turbo_frame_tag 'flash' do
  = render 'flash'

-# game
= turbo_stream_from @game
= render @game

-# detail modal
= turbo_stream_from dom_id(@game, 'detail')
= turbo_frame_tag "detail_modal" do
  = render 'detail_modal'

-# finish modal
= turbo_stream_from dom_id(@game, 'finish')
= turbo_frame_tag "finish_modal" do
  = render 'finish_modal'