config/routes.rb
Rails.application.routes.draw do
  root 'static#index'
  get '/terms', to: 'static#terms'
  get '/rules', to: 'static#rules'
  get '/credits', to: 'static#credits'
  get '/privacy_policy', to: 'static#privacy_policy'

  resources :games, only: %i[index show create destroy], shallow: true do
    member do
      get :paticipates
    end
    resources :users, only: %i[edit], shallow: true do
      post :authorize
      resources :user_hands, only: %i[show edit destroy]
      resources :user_supports, only: %i[edit destroy]
    end
    resources :game_details, only: %i[index]
  end

  resources :cpu_games, only: %i[show create destroy], shallow: true do
    resources :users, only: %i[show edit], shallow: true do
      resources :user_hands, only: %i[show edit destroy]
      resources :user_supports, only: %i[show edit destroy]
    end
    resources :game_details, only: %i[index]
  end

  get '/login_as/:user_id', to: 'dev/user_sessions#login_as' unless Rails.env.production?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :require_login
  helper_method :secret_clearance

  def secret_clearance
    session[:clearance].presence || false
  end

  def require_login
    redirect_to root_path unless current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: '旧約じゃんけん',
      title: '旧約じゃんけん',
      reverse: true,
      charset: 'utf-8',
      description: 'ルールがちょっと複雑なじゃんけんゲーム。',
      keywords: '旧約じゃんけん,old-janken',
      canonical: request.original_url,
      separator: '|',
      icon: [
        { href: "#{root_url}favicon.ico" },
        { href: "#{root_url}apple-touch-icon.png", rel: 'apple-touch-icon', sizes: '180x180', type: 'image/png' },
      ],
      og: {
        site_name: :site,
        title: :title,
        description: :description,
        type: 'website',
        url: request.original_url,
        image: "#{root_url}ogp.png",
        locale: 'ja_JP',
      },
      twitter: {
        site_name: :site,
        title: :title,
        description: :description,
        card: 'summary_large_image',
        site: '@old-janken',
        image: "#{root_url}ogp.png",
      },
    }
  end

  def game_detail_page?
    %w[root rules terms credits privacy_policy games].any? do |name|
      !current_page?(send("#{name}_path"))
    end
  end

  def cpu_game?(game)
    game.guest.user_token_digest == 'cpu_token'
  end

  def icon(icon_name)
    tag.i(class: ['bi', "bi-#{icon_name}"])
  end

  def icon_with_text(icon_name, text)
    tag.span(icon(icon_name), class: 'me-2') + tag.span(text)
  end

  def turbo_stream_flash
    turbo_stream.append 'flashes', partial: 'flash'
  end

  def turbo_stream_background
    turbo_stream.replace 'background', partial: 'background'
  end
end

app/views/application/_background.html.haml
#background.game.d-flex.justify-content-center{ class: game.field.card_image.gsub('fields/', '').gsub('.png', '') }
 = yield

app/views/application/_card.html.haml
:ruby
  if card_role.attributes.has_key?("support_id")
    edit_path = edit_user_support_path(card_role, game_id: @game.id)
  elsif card_role.attributes.has_key?("hand_id")
    edit_path = edit_user_hand_path(card_role, game_id: @game.id)
  else
    edit_path = edit_user_path(card_role)
  end

- if !card_role.attributes.has_key?("character_id") && enemy?(card_role.user)
  = image_tag 'cards/card-back.png', class: 'card mx-4 enemy-card non-character-card'

- elsif card_role.attributes.has_key?("character_id") && enemy?(card_role)
  = link_to edit_path, data: { turbo_frame: "modal" } do
    = image_tag card_role.character.card_image, class: "card mx-4 enemy-card"

- elsif card_role.attributes.has_key?("character_id")
  = link_to edit_path, data: { turbo_frame: "modal" } do
    = image_tag card_role.character.card_image, class: "card mx-4"

- elsif card_role.attributes.has_key?("support_id")
  = link_to edit_path, data: { turbo_frame: "modal" } do
    = image_tag card_role.support.card_image, class: "card mx-4"

- elsif card_role.attributes.has_key?("hand_id")
  = link_to edit_path, data: { turbo_frame: "modal" } do
    = image_tag card_role.hand.card_image, class: "card mx-4"

app/views/application/_detail_modal.html.haml
- if defined?(host_game_detail) && defined?(guest_game_detail)
  .modal.fade{ data: { controller: "modal" } }
    .modal-dialog.modal-dialog-centered
      .modal-content
        .modal-header
          %h5.modal-title
            = host_game_detail.round_num
          %button.btn-close{ type:"button", data: { 'bs-dismiss': "modal" }, 'aria-label': "Close"}
        .modal-body.d-flex.justify-content-between
          %div
            host
            = image_tag host_game_detail.hand.card_image, class: "card mx-4"
          %div
            guest
            = image_tag guest_game_detail.hand.card_image, class: "card mx-4"

app/views/application/_finish_modal.html.haml
= turbo_frame_tag "finish_modal" do
  - if defined?(game_details)
    .modal.fade{ data: { controller: "modal" } }
      .modal-dialog.modal-dialog-centered
        .modal-content
          .modal-header
            %h5.modal-title
              - if game_details.present?
                - if game_details.last.game.game_details.last.finished?
                  = game_details.last.game.winner_role
                - else
                  ゲーム詳細
              - else
                表示する結果が見つかりませんでした。
            %button.btn-close{ type:"button", data: { 'bs-dismiss': "modal" }, 'aria-label': "Close"}
          .modal-body.d-flex.justify-content-between.overflow-scroll
            = render game_details

app/views/application/_flash.html.haml
- if defined?(message)
  #flashes
    .mb-2.toast.hide.border-default{ data: { controller: "toast" } }
      .toast-body.d-flex.justify-content-between.text-default
        %strong.me-auto
          = icon_with_text("check-circle", message)
        %button.btn-close{ data: { 'bs-dismiss': "toast" } }

app/views/application/_fullscreen_modal.html.haml
= turbo_frame_tag "fullscreen_modal" do
  .modal.fade{ data: { controller: "modal" } }
    .modal-dialog.modal-xl
      .modal-content
        .modal-header
          %h5.modal-title
            = title
          %button.btn-close{ type:"button", data: { 'bs-dismiss': "modal" }, 'aria-label': "Close"}
        .modal-body.overflow-scroll
          = yield

app/views/application/_modal.html.haml
= turbo_frame_tag "modal" do
  .modal.fade{ data: { controller: "modal" } }
    .modal-dialog.modal-dialog-centered
      .modal-content
        .modal-header
          %h5.modal-title
            = card.name
          %button.btn-close{ type:"button", data: { 'bs-dismiss': "modal" }, 'aria-label': "Close"}
        .modal-body.d-flex.justify-content-between
          %p.text-break.lh-lg.mx-3.w-50= card.description
          = image_tag card.card_image, class: "card mx-4"
        - if my_turn?(@game.game_details.last) && card.type != 'character'
          .modal-footer
            = yield

app/views/application/_offcanvas.html.haml
.offcanvas.offcanvas-start{ tabindex: "-1", id: "offcanvas", 'aria-labelledby': "offcanvasLabel"}
  .offcanvas-header
    = image_tag 'logo.png', {id: 'logo'}
    %button{ type: "button", class: "btn-close text-reset", 'data-bs-dismiss': "offcanvas", 'aria-label': "Close" }
  .offcanvas-body
    %ul
      %li.m-3
        = link_to root_path, class: 'text-black' do
          %i.bi.bi-house-door-fill &nbsp;&nbsp;&nbsp;トップページ
      - if ! game_detail_page?
        %li.m-3
          = button_to cpu_games_path, method: :post, class: 'btn btn-default p-0' do
            %i.bi.bi-controller &nbsp;&nbsp;&nbsp;CPU対戦
        %li.m-3
          = button_to games_path, method: :post, class: 'btn btn-default p-0' do
            %i.bi.bi-controller &nbsp;&nbsp;&nbsp;リアルタイム対戦
      - if defined?(@game)
        %li.m-3
          = link_to game_game_details_path(@game), class: 'text-black', data: { turbo_frame: "finish_modal" } do
            %i.bi.bi-ticket-detailed-fill &nbsp;&nbsp;&nbsp;ラウンド結果
      - if defined?(@game) && current_page?(game_path(@game))
        %li.m-3
          = link_to "https://twitter.com/intent/tweet?text=対戦相手募集中！%0A#{request.url}/paticipates/%0A&hashtags=旧約じゃんけん,クソアプリWeek&via=old_janken", target: :_blank, rel: "noopener noreferrer" do
            %i.bi.bi-twitter &nbsp;&nbsp;&nbsp;対戦相手を募集
        %li.m-3
          = link_to "https://line.me/R/msg/text/?対戦相手募集中！%0A#{request.url}/paticipates/", target: :_blank, rel: "noopener noreferrer" do
            %i.bi.bi-line &nbsp;&nbsp;&nbsp;対戦相手を募集
        %li.m-3{ data: { controller: "clipboard" } }
          %input{ type: "hidden", data: { 'clipboard-target': "source" }, value: "#{request.url}/paticipates/" }
          %button{ data: { action: "click->clipboard#copy" }, class: "btn btn-default p-0" }
            %i.bi.bi-link-45deg &nbsp;&nbsp;&nbsp;募集リンクを表示
      %li.m-3
        = link_to rules_path, class: 'text-black', data: { turbo_frame: "fullscreen_modal" } do
          %i.bi.bi-card-text &nbsp;&nbsp;&nbsp;ルール
      %li.m-3
        = link_to terms_path, class: 'text-black', data: { turbo_frame: "fullscreen_modal" } do
          %i.bi.bi-book &nbsp;&nbsp;&nbsp;利用規約
      %li.m-3
        = link_to credits_path, class: 'text-black', data: { turbo_frame: "fullscreen_modal" } do
          %i.bi.bi-bookmark-check &nbsp;&nbsp;&nbsp;クレジット
      %li.m-3
        = link_to privacy_policy_path, class: 'text-black', data: { turbo_frame: "fullscreen_modal" } do
          %i.bi.bi-shield-fill-check &nbsp;&nbsp;&nbsp;プライバシーポリシー
      %li.m-3
        = link_to "https://twitter.com/old_janken", class: 'text-black', target: :_blank, rel: "noopener noreferrer" do
          %i.bi.bi-twitter &nbsp;&nbsp;&nbsp;問い合わせ
      - if defined?(@game)
        .m-3
          = audio_tag("game_music.mp3", autoplay: true, controls: true, loop: true, data: {turbo: 'permanent'})

app/views/application/_paticipates.html.haml
.modal.fade{ data: { controller: "modal" } }
  .modal-dialog.modal-xl
    .modal-content
      .modal-header
        %h5.modal-title 対戦相手を募集
        %button.btn-close{ type:"button", data: { 'bs-dismiss': "modal" }, 'aria-label': "Close"}
      .modal-body.overflow-scroll.paticipates
        %ul
          %li.m-3
            = link_to "https://twitter.com/intent/tweet?text=対戦相手募集中！%0A#{request.url}/paticipates/%0A&hashtags=旧約じゃんけん,クソアプリWeek&via=old_janken", target: :_blank, rel: "noopener noreferrer" do
              %i.bi.bi-twitter &nbsp;&nbsp;&nbsp;Twitterで募集
          %li.m-3
            = link_to "https://line.me/R/msg/text/?対戦相手募集中！%0A#{request.url}/paticipates/", target: :_blank, rel: "noopener noreferrer" do
              %i.bi.bi-line &nbsp;&nbsp;&nbsp;LINEで募集
          %li.m-3{ data: { controller: "clipboard" } }
            %input{ type: "hidden", data: { 'clipboard-target': "source" }, value: "#{request.url}/paticipates/" }
            %button{ data: { action: "click->clipboard#copy" }, class: "btn btn-default p-0" }
              %i.bi.bi-link-45deg &nbsp;&nbsp;&nbsp;募集リンクを表示